### ISSUE TITLE
Thank you for creating this plugin!

### ISSUE THREAD

**Issue by paaljoachim** [emfluencekc/multisite-multidomain-single-sign-on#1]
Hi @emfluencekc 

I am recreating my tutorial on useful Multisite plugins and this plugin is one that is very useful to include.
Perhaps you could brush it up and add it directly to the WP repo as an official plugin?

I will assume that the reason this feature even though it is very useful has not already been added to core is that it might impact security.

Thanks!

Tutorial is being updated and the site is getting a total makeover.
https://www.easywebdesigntutorials.com/multisite-plugins/

**Comment by emfluencekc** [comment]
Hi @paaljoachim! 

We appreciate that you've found this plugin valuable. We created it to work better with our own clients and have been happy to share it.

This plugin is currently published in the wordpress.org plugin repository: 
https://wordpress.org/plugins/multisite-multidomain-single-sign-on/

The plugin was reviewed manually and approved for use on their own hosting platform by the Automattic team, through the Wordpress VIP program. They did express that the plugin widens the security perimeter, and we had a discussion about risk vs convenience. It's somewhat like installing a SSO integration plugin.

We never talked with Automattic about the idea of adding the functionality to Wordpress core, though we'd be happy if that did happen. Automattic may simply see it as a niche area of functionality not worth further effort on their part... I'm not sure about the statistics of single-domain vs multi-domain multisite installs in the wild. If you are familiar with those stats, we'd love to see them.

Cheers!

**Comment by paaljoachim** [comment]
Thank you for your response, @emfluencekc 

I went ahead and added a link into the WordPress Slack channel core-multisite:
https://wordpress.slack.com/archives/C03BVB47S/p1629027831026000
(Needs signing up though.)
